### ISSUE TITLE
Failure on ubuntu-18.04

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [Chocobo1/setup-ccache-action#1]
The action always fails on ubuntu-18.04.

Example run:

https://github.com/AllSeeingEyeTolledEweSew/libtorrent/runs/3711450909?check_suite_focus=true

The error seems to be:

```
 /usr/bin/ccache --show-config
  /usr/bin/ccache: unrecognized option '--show-config'
  Usage:
...
```

**Comment by Chocobo1** [comment]
Thanks for reporting. I'll make a new release in a day or two.
