### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by Vollstrecker** [Chocobo1/setup-ccache-action#11]
Hi,

I tried to also make use of this action in combination with cygwin.

First the good news: The binary is found (thanks to that cygwin is added to the path).

And now the bad news: First thing I saw was the version check. It finds the binary from cygwin and the one from choco and doesn't seem to b able to handle this. It calls "bin1 bin2 --version" which just can't work. I was able to work around this by deleting the choco ccache.exe (Uninstalling didn't work as choco claims it didn't install it).

Second problem: cygwin ships ccache 3.1.9 which doesn't have --get-config and also doesn't have -p option:

`c:\cygwin64\bin\ccache.exe -h`
`Usage:`
`    ccache [options]`
`    ccache compiler [compiler options]`
`    compiler [compiler options]          (via symbolic link)`

`Options:`
`    -c, --cleanup         delete old files and recalculate size counters`
`                          (normally not needed as this is done automatically)`
`    -C, --clear           clear the cache completely`
`    -F, --max-files=N     set maximum number of files in cache to N (use 0 for`
`                          no limit)`
`    -M, --max-size=SIZE   set maximum size of cache to SIZE (use 0 for no`
`                          limit; available suffixes: G, M and K; default`
`                          suffix: G)`
`    -s, --show-stats      show statistics summary`
`    -z, --zero-stats      zero statistics counters`

`    -h, --help            print this help text`
`    -V, --version         print version and copyright information`

Cache-dir could be parsed from -s output:

`c:\cygwin64\bin\ccache.exe -s`
`cache directory                     /home/micro/.ccache`
`cache hit (direct)                   171`
`cache hit (preprocessed)               0`
`cache miss                           172`
`files in cache                       516`
`cache size                          79.2 Mbytes`
`max cache size                       1.0 Gbytes`

Would be great if you could add cygwin, as it seems to be the only plattfrom that's missing. If you need some additional info, just let me know.

**Comment by Chocobo1** [comment]
I'm not familiar with Cygwin but I might able to look into it. First I need a minimal github actions workflow to toy with, one that will setup cygwin and compile hello_world.cpp and execute it. Are you able to help with that?

>Second problem: cygwin ships ccache 3.1.9 which doesn't have --get-config and also doesn't have -p option:

Hmm, in this case, I suppose I could just omit this command. But seeing that ccache 3.1.9 support too few cmd arguments, I'm afraid I might run into other severe issues in later steps.
Can't cygwin update it to a more recent version?
or can the ccache installed from choco work with cygwin?

**Comment by Vollstrecker** [comment]
Beside the problem with 2 binaries, most of the stuff seems to work except restoring and saving the cache. I don't fully understand the language used here (to be honest I don't even know which one it is) but from reading the source I can only the --set-config which would be missing. I don't know why this is needed, or if it's also missing in the older Ubuntu version (is this one still available as a runner?) but I guess just overwriting the file would work also.

For an example run what's missing you can look [here](https://github.com/abdes/cryptopp-cmake/actions/runs/4670854088/jobs/8271098810)

Using the one in windows doesn't work. I didn't dig that deep, but it seems that calling cygwin binaries from outside works, but not the other way. Maybe it's just a path problem.

If you have anything that should be tried for this (if you take effort) I would happily test it (as soon as I find out how to import dev-branches of actions.

**Comment by Chocobo1** [comment]
It seems that ccache 3.1.9 is really just too old for it to be supported for this project. Without the required command arguments (`--set-config` is one and there are a few others) there really isn't much that this project could do.

I can think of 2 ways to go forward:
1. Update cygwin ccache package to a modern version
  One can follow the instructions here: https://www.cygwin.com/packaging-contributors-guide.html
  And afterwards I may able to add support for it.
2. Or you can handle the build cache (of ccache) yourself/manually by using [actions/cache](https://github.com/actions/cache)

**Comment by Vollstrecker** [comment]
As I don't even have Win here updating (and maybe maintaining) this will be almost impossible for me. I guess I first try to get somehow the version in the containing windows used and second compile a recent version on the runner (maybe giving the result back to you).
