### ISSUE TITLE
brew exit code 1

### ISSUE THREAD

**Issue by Vollstrecker** [Chocobo1/setup-ccache-action#12]
Hi, after paying more attention at the annotations because of the 1.14 update (nice fix, works, thanks), I've seen one more. When giving just the make version and laving all other opts at default I get this output:

` ==> Installing ccache dependency: hiredis`
`  ==> Pouring hiredis--1.1.0.monterey.bottle.tar.gz`
`  Warning: The post-install step did not complete successfully`
`  You can try again using:`
`    brew postinstall hiredis`
`  ==> Summary`
`  🍺  /usr/local/Cellar/hiredis/1.1.0: 41 files, 365.1KB`
`  ==> Installing ccache`
`  ==> Pouring ccache--4.8.monterey.bottle.tar.gz`
`  Warning: The post-install step did not complete successfully`
`  Warning: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK is set: not checking for outdated`
`  dependents or dependents with broken linkage!`
`  You can try again using:`
`    brew postinstall ccache`
`  ==> Caveats`
`  To install symlinks for compilers that will automatically use`
`  ccache, prepend this directory to your PATH:`
`    /usr/local/opt/ccache/libexec`
`  `
`  If this is an upgrade and you have previously added the symlinks to`
`  your PATH, you may need to modify it to the path specified above so`
`  it points to the current version.`
`  `
`  NOTE: ccache can prevent some software from compiling.`
`  ALSO NOTE: The brew command, by design, will never use ccache.`
`  ==> Summary`
`  🍺  /usr/local/Cellar/ccache/4.8: 75 files, 1.4MB`
`  ==> Caveats`
`  ==> ccache`
`  To install symlinks for compilers that will automatically use`
`  ccache, prepend this directory to your PATH:`
`    /usr/local/opt/ccache/libexec`
`  `
`  If this is an upgrade and you have previously added the symlinks to`
`  your PATH, you may need to modify it to the path specified above so`
`  it points to the current version.`
`  `
`  NOTE: ccache can prevent some software from compiling.`
`  ALSO NOTE: The brew command, by design, will never use ccache.`
`  Warning: The process '/usr/local/bin/brew' failed with exit code 1`

`I'm not sure if this is by design (of brew) or avoidable, but I know it's annoying as it's the only annotation left in the workflow.

**Comment by Chocobo1** [comment]
I noticed it for some time and I personally believe it was `brew` behaving wrong (wrong exit code for that situation).
Anyway I suppressed it in 09f7685d1e62dcc251dd9352f0582b0162b278a8.
