### ISSUE TITLE
Brew install failing on macOS runners

### ISSUE THREAD

**Issue by burgholzer** [Chocobo1/setup-ccache-action#14]
Hi 👋🏼
Thanks for maintaining this nice action!

Since a couple of days ago, we are experiencing some problems on macOS runners, where the action fails to install ccache via brew.
More precisely, it fails with the following warning
```console
/usr/local/bin/brew install ccache
  Error: $HOME must be set to run brew.
```
See https://github.com/cda-tum/mqt-core/actions/runs/5809540441/job/15748518266#step:3:168 for an example run that fails.

Some googling brings up https://github.com/Homebrew/brew/issues/15833, which describes that a change has been introduced quite recently and `$HOME` needs to be specified now.

What I suspect is happening is that the process that the `brew` command is running in does not have access to the `$HOME` env variable that is automatically set by GitHub Actions. A potential solution could be to just pass that variable through here:
https://github.com/Chocobo1/setup-ccache-action/blob/cfe53952d080560153e4464869bfda626ebac7cd/src/main.ts#L87-L90

I'll happily submit a PR if you feel that that might be a proper solution.

**Comment by burgholzer** [comment]
Great! Thanks for the quick response!

**Comment by Chocobo1** [comment]
v1.3.9 is now released and it will address this issue. Closing issue.
