### ISSUE TITLE
Should configure ccache before restore cache

### ISSUE THREAD

**Issue by zhongfly** [Chocobo1/setup-ccache-action#17]
If set cache_dir to another place,it will make restore cache never success.
Example:
```
- name: Set up ccache
  uses: Chocobo1/setup-ccache-action@v1
  with:
    ccache_options: |
      cache_dir=${{ env.workspace }}/.ccache
```
So I think it should configure ccache before restore cache.

**Comment by zhongfly** [comment]
One thing more, don't run `updatePackgerIndex` if `install_ccache` is false.

**Comment by Chocobo1** [comment]
>If set cache_dir to another place,it will make restore cache never success.

I resolved it in 64fc5fdd80f00431cc6f8d47abec819cc41bf49f.
Thanks for reporting!

**Comment by zhongfly** [comment]
Still have problem with env:
example:`cache_dir=$GITHUB_WORKSPACE/.ccache` will fail to restore cache
You can find `$GITHUB_WORKSPACE` in https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

@Chocobo1 my pr can fix this, but https://github.com/Chocobo1/setup-ccache-action/commit/64fc5fdd80f00431cc6f8d47abec819cc41bf49f can't.

**Comment by Chocobo1** [comment]
>example:cache_dir=$GITHUB_WORKSPACE/.ccache

Strictly speaking it is invalid to use environment variables here. Use `cache_dir=${{ github.workspace }}/.ccache` instead.
Here we are not invoking ccache via shell but from "github actions" context so environment variables aren't resolved (at least github actions chooses not to).
However, I do agree that this is a bit unexpected for the common users. I'll ponder on it.

>In my opinion, https://github.com/Chocobo1/setup-ccache-action/pull/19 simply solves the problem and avoids the bugs that restore cache and save cache use different paths

I'm concerned that if the ccache config resides within the cache path and after cache restore it will overwritten the configuration. I don't consider it correct.

**Comment by Chocobo1** [comment]
>Strictly speaking it is invalid to use environment variables here. Use cache_dir=${{ github.workspace }}/.ccache instead.
Here we are not invoking ccache via shell but from "github actions" context so environment variables aren't resolved (at least github actions chooses not to).

I think this is the relevant documentation: 
https://docs.github.com/en/actions/learn-github-actions/variables#using-the-env-context-to-access-environment-variable-values
>The run steps in a workflow, or in a referenced action, are processed by a runner. As a result, you can use runner environment variables here, using the appropriate syntax for the shell you are using on the runner - for example, $NAME for the bash shell on a Linux runner, or `$env:NAME` for PowerShell on a Windows runner. In most cases you can also use contexts, with the syntax ${{ CONTEXT.PROPERTY }}, to access the same value. The difference is that the context will be interpolated and replaced by a string before the job is sent to a runner.
>
>**However, you cannot use runner environment variables in parts of a workflow that are processed by GitHub Actions and are not sent to the runner. Instead, you must use contexts.**

And as I mentioned, setup-ccache-action is processed by GitHub Actions not via a runner/shell.

https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
>However, most of the default variables have a corresponding, and similarly named, context property. For example, the value of the GITHUB_REF variable can be read during workflow processing using the ${{ github.ref }} context property.

Also it seems to me that github have already known this (downside) and decided to provide both context properties and runner env variables.

**Comment by zhongfly** [comment]
> Strictly speaking it is invalid to use environment variables here. Use cache_dir=${{ github.workspace }}/.ccache instead.

> In most cases you can also use contexts, with the syntax ${{ CONTEXT.PROPERTY }}, to access the same value.

Yes, but `$GITHUB_WORKSPACE` and `${{ github.workspace}} ` are different for job run in a container.
see this https://github.com/actions/checkout/issues/785 and https://github.com/actions/runner/issues/2058

**Comment by zhongfly** [comment]
I think the main problem is that the paths to save cache and restore cache have to be exactly the same in terms of characters.
Either both prioritize the value of `ccache_options` or both prioritize the value in the config file. Instead of using different values as it is now

**Comment by Chocobo1** [comment]
>${{ github.workspace }} is /home/runner/work/..., but $GITHUB_WORKSPACE is /__w/...
>
>Github action does have some weirdness to it.

True and they still haven't address it yet...

Not sure if you are still looking for a workaround but just in case, perhaps the following will work:
```yaml
  # export variable
  - run: echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
  # use variable
  - name: Set up ccache
    uses: Chocobo1/setup-ccache-action@v1
    with:
      ccache_options: |
        cache_dir=${{ env.GITHUB_WORKSPACE }}/.ccache
```

**Comment by zhongfly** [comment]
Earlier you talked about the possibility of overwriting the config file when restoring cache, so set the option after restoring.So maybe we can set the option `cache_dir` both before and after restore
