### ISSUE TITLE
Cache upload failed - ESPIPE: invalid seek

### ISSUE THREAD

**Issue by silverqx** [Chocobo1/setup-ccache-action#7]
Hi @Chocobo1, today all my ccache actions calls started failing, it's a first time I see any problem with this action.

Here is the link to the [failed action](https://github.com/silverqx/TinyORM/runs/6856356016?check_suite_focus=true#step:29:24).

It fails with this error:
```
Error: Cache upload failed because file read failed with ESPIPE: invalid seek, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/Chocobo1/setup-ccache-action/v1/dist/webpack:/@Chocobo1/setup-ccache-action/node_modules/@actions/cache/lib/internal/cacheHttpClient.js:180:1)
```

Do your ccache actions work?

**Comment by silverqx** [comment]
Already works

**Comment by silverqx** [comment]
But still only some pipelines, do you know what it means?

**Comment by silverqx** [comment]
I have another error:
```
 Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
      at ReadStream.<anonymous> (/home/runner/work/_actions/Chocobo1/setup-ccache-action/v1/dist/webpack:/@Chocobo1/setup-ccache-action/node_modules/@actions/cache/lib/internal/cacheHttpClient.js:180:1)
```

It looks like the storage array is failing? How can I workaround this, should I disable ccache for a while?

**Comment by Chocobo1** [comment]
From your build log:
>Warning: uploadChunk (start: 0, end: 33554431) failed: Cache service responded with 503

I think it is github having some hiccups, probably some reliability issues. They should be resolved in no time.

>I have another error:
>Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read

I think it is the same as above, github hiccups.

However I consider this ccache action shouldn't error out on this kind of issue. I have pushed an update to suppress the errors.

**Comment by silverqx** [comment]
> However I consider this ccache action shouldn't error out on this kind of issue. I have pushed an update to suppress the errors.

Ok, thx, all my CI finished successfully now.
